spring:
#Configuración MySQL
  mail:
    host: smtp.gmail.com
    port: 587
    username: challengejavaalkemy
    password: backendonly
    properties:
        mail:
            smtp:
                auth: true
                starttls:
                    required: true
                    enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/alkemyproyect?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#Configuración Creación de tablas (Hibernate)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#Para que thymeleaf no guarde datos en cache
    thymeleaf:
      cache: false
  
